Repository LIKELION-SOGANG/LIKELION-WEBSITE-NEXTJS, pull requests merged in 2024-09, with the labels that each got.

#14 tailwind config 수정, Header 스타일 바꾸기
  package-lock.json
  src/app/about/container/Onboard1.tsx
  src/app/about/container/Onboard2.tsx
  src/app/about/container/Onboard3.tsx
  src/app/about/container/Onboard4.tsx
  src/app/about/container/Onboard5.tsx
  src/app/about/page.tsx
  src/app/common/Header.tsx
  tailwind.config.ts
Labels: bug, Style

#20 PEOPLE 페이지 중간점검
  src/app/people/container/People1.tsx
  src/app/people/container/People2.tsx
  src/app/people/container/TabContents.tsx
  src/app/people/page.tsx
Labels: feature

#24 ABOUT 페이지 중간점검
  public/icon/logo/stack/aws.png
  public/icon/logo/stack/css.png
  public/icon/logo/stack/react.png
  src/app/about/container/Onboard1.tsx
  src/app/about/container/Onboard2.tsx
  src/app/about/container/Onboard3.tsx
  src/app/about/container/Onboard4.tsx
  src/app/about/container/Onboard5.tsx
  src/app/about/page.tsx
  tailwind.config.ts
Labels: Style

#23 RECRUIT 페이지 중간점검
  next.config.mjs
  package-lock.json
  package.json
  src/app/AreaItem.tsx
  src/app/FAQItem.tsx
  src/app/ScheduleItem.tsx
  src/app/recruit/ScrollLottie.tsx
  src/app/recruit/apply/ApplyHeader.tsx
  src/app/recruit/apply/Button.tsx
  src/app/recruit/apply/CheckingPass.tsx
  src/app/recruit/apply/LargeInput.tsx
  src/app/recruit/apply/Nonpassed.tsx
  src/app/recruit/apply/Passed.tsx
  src/app/recruit/apply/Progress.tsx
  src/app/recruit/apply/SaveButton.tsx
  src/app/recruit/apply/SelectPart.tsx
  src/app/recruit/apply/SelectTimeDay.tsx
  src/app/recruit/apply/SmallInput.tsx
  src/app/recruit/apply/container/ApplySection.tsx
  src/app/recruit/apply/container/EditPersonalInfo.tsx
  src/app/recruit/apply/container/PersonalInformationForm.tsx
  src/app/recruit/apply/container/PersonalStatementForm.tsx
  src/app/recruit/apply/container/SaveComplete.tsx
  src/app/recruit/apply/page.tsx
  src/app/recruit/container/Recruit1.tsx
  src/app/recruit/container/Recruit2.tsx
  src/app/recruit/page.tsx
  src/custom.d.ts
  src/utils/recruitMockData.ts
  tsconfig.json
Labels: feature

#26 Midterm Inspection (중간점검)
  .env
  .gitignore
  package-lock.json
  package.json
  src/app/contact/container/.gitkeep
  src/app/page.tsx
  src/app/people/container/.gitkeep
  src/app/project/container/.gitkeep
  src/app/recruit/ScheduleItem.tsx
  src/app/recruit/apply/components/ApplyHeader.tsx
  src/app/recruit/apply/components/Button.tsx
  src/app/recruit/apply/components/CheckingPass.tsx
  src/app/recruit/apply/components/LargeInput.tsx
  src/app/recruit/apply/components/Nonpassed.tsx
  src/app/recruit/apply/components/Passed.tsx
  src/app/recruit/apply/components/Progress.tsx
  src/app/recruit/apply/components/SaveButton.tsx
  src/app/recruit/apply/components/SelectPart.tsx
  src/app/recruit/apply/components/SelectTimeDay.tsx
  src/app/recruit/apply/components/SmallInput.tsx
  src/app/recruit/apply/container/ApplySection.tsx
  src/app/recruit/apply/container/EditPersonalInfo.tsx
  src/app/recruit/apply/container/PersonalInformationForm.tsx
  src/app/recruit/apply/container/PersonalStatementForm.tsx
  src/app/recruit/apply/page.tsx
  src/app/recruit/components/AreaItem.tsx
  src/app/recruit/components/FAQItem.tsx
  src/app/recruit/container/.gitkeep
  src/app/recruit/container/Recruit2.tsx
  src/app/recruit/page.tsx
  src/custom.d.ts
  tailwind.config.ts
Labels: chore

#30 ABOUT 페이지 마크업 완료
  package-lock.json
  src/app/about/container/Onboard1.tsx
  src/app/about/container/Onboard2.tsx
  src/app/about/container/Onboard3.tsx
  src/app/about/container/Onboard4.tsx
  src/app/about/container/Onboard5.tsx
  src/custom.d.ts
  tailwind.config.ts
Labels: Style

#31 RECRUIT 페이지 마크업 완료
  src/app/recruit/ScheduleItem.tsx
  src/app/recruit/apply/Nonpassed.tsx
  src/app/recruit/apply/Passed.tsx
  src/app/recruit/components/AreaItem.tsx
  src/app/recruit/components/FAQItem.tsx
  src/app/recruit/container/Recruit1.tsx
  src/app/recruit/container/Recruit2.tsx
Labels: Style, chore

#28 CONTACT 페이지 마크업 완료
  public/images/contact/obj3.png
  src/app/contact/container/Contact1.tsx
  src/app/contact/container/Contact2.tsx
  src/app/contact/page.tsx
Labels: feature

#35 CREDIT PAGE 마크업 완료
  package-lock.json
  public/images/credit/sgLogo-Black.png
  src/app/credit/page.tsx
Labels: Style, feature
