Repository LIKELION-SOGANG/LIKELION-WEBSITE-NEXTJS, pull requests merged in 2024-10, with the labels that each got.

#39 PEOPLE 페이지 fetch API 연동 완료
  src/app/people/components/TabItem.tsx
  src/app/people/container/People2.tsx
  src/app/people/page.tsx
Labels: feature

#56 ESLINT 설정 및 .vscode 폴더 세팅
  .eslintrc.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/(apply)/apply/components/Button.tsx
  src/app/(apply)/apply/container/ApplySection.tsx
  src/app/(apply)/apply/container/EditPersonalInfo.tsx
  src/app/(apply)/apply/page.tsx
  src/app/(apply)/layout.tsx
  src/app/(main)/about/container/Onboard3.tsx
  src/app/(main)/about/container/Onboard4.tsx
  src/app/(main)/project/[id]/page.tsx
  src/app/(main)/project/container/components/TabBtn.tsx
  src/app/(main)/recruit/components/FAQItem.tsx
  src/app/(main)/recruit/components/PCOnly.tsx
  src/app/(main)/recruit/components/ScrollLottie.tsx
  src/app/(main)/recruit/container/PcOnly.tsx
  src/app/(main)/recruit/container/Recruit1.tsx
  src/app/(main)/recruit/container/Recruit2.tsx
  src/app/(main)/recruit/page.tsx
  src/app/component/Footer.tsx
  src/style/zIndex.ts
Labels: chore

#63 Feat: Add TF members in credit page #58
  src/app/(main)/credit/page.tsx
Labels: feature

#62 헤더 사용선 개선 및 페이지 이동 시 전환 효과 추가
  .github/CODEOWNERS
  package-lock.json
  package.json
  src/app/component/Header.tsx
  src/app/component/Loading.tsx
  src/hooks/.gitkeep
  src/hooks/useLoadingProgress.ts
  src/hooks/useMobileMenu.ts
  src/hooks/useScrollDirection.ts
  tailwind.config.ts
Labels: Style, refactor, feature

#66 PEOPLE 페이지 기수 컴포넌트 개선
  public/images/people/MockImages/김유이.svg
  public/images/people/MockImages/오은택.svg
  public/images/people/MockImages/이선명.svg
  public/images/people/MockImages/임정연.svg
  public/images/people/MockImages/장세환.svg
  public/images/people/MockImages/정고은.svg
  public/images/people/MockImages/정인영.svg
  src/app/(main)/people/components/TabItem.tsx
  src/app/(main)/people/container/People2.tsx
Labels: bug, feature

#64 Feature/apply page interaction#59
  .eslintrc.json
  .prettierrc
  src/app/(apply)/apply/components/CheckingPass.tsx
  src/app/(apply)/apply/components/Progress.tsx
  src/app/(apply)/apply/components/SelectTimeDay.tsx
  src/app/(apply)/apply/components/SmallInput.tsx
  src/app/(apply)/apply/container/ApplySection.tsx
  src/app/(apply)/apply/container/EditPersonalInfo.tsx
  src/app/(apply)/apply/container/PCOnly.tsx
  src/app/(apply)/apply/container/PersonalInformationForm.tsx
  src/app/(apply)/apply/container/PersonalStatementForm.tsx
  src/app/(apply)/apply/container/SaveComplete.tsx
  src/app/(apply)/apply/page.tsx
  src/app/(apply)/layout.tsx
  src/app/(main)/recruit/components/FAQItem.tsx
  src/app/(main)/recruit/components/ScrollLottie.tsx
  src/app/(main)/recruit/container/PcOnly.tsx
  src/app/(main)/recruit/container/Recruit1.tsx
  src/app/(main)/recruit/page.tsx
Labels: feature

#68 `Contact` 페이지 오브젝트 이미지 애니메이션 구현
  package-lock.json
  package.json
  src/app/(main)/contact/container/Contact1.tsx
  src/hooks/useSequencialAnimation.ts
  tailwind.config.ts
  tsconfig.json
Labels: feature
